### ISSUE TITLE
add "best of" teacher tool to class setup tool

### ISSUE THREAD

**Issue by stevenolen** [mobilizingcs/classes#26]
To help generalize mobilize for a deployment beyond lausd, here are the things @jeroenooms and I discussed to make this tool work a bit better for mobilize:

Make class tool have mobilize features as well:
- Add print view for easier printing of created accounts.
- on `app_name=ohmage`
  - Demo Campaign list with sample campaigns to add to class
- on `app_name=mobilize`
  - remove "Demo Campaigns"
  - add Curriculum Type (single choice): IDS, Math, Science
  - add tool tip to "Class Name" suggesting that a period/semester be used to better identify the class.

**Comment by hongsudt** [comment]
sounds good.. 2 comments:
- Is the drop down list for year currently automatically generated? If not,
  can we make it so.. Otherwise, we need to make a note for lausd to manually
  change it.
- Steve: you might have to ask rob/suyen whether they want to change math
  to algebra1 and science to biology to be more specific.. We discussed being
  more specific with curriculum names in the past.

**Comment by stevenolen** [comment]
- the semester list is automatically generated.
- I'll ask about the specificity!

**Comment by jeroen** [comment]
OK I have implemented the curriculum picker and print button. I did it slightly different because I don't like to have different views for `app_name`. There is now an extra curriculum named `demo` which is used to pick your own campaigns.

**Comment by stevenolen** [comment]
This is cool! Perhaps instead of a "Demo" curriculum, we could call it "No curruculum" or "Free Form" or something?

**Comment by jeroen** [comment]
OK. The print view and curriculum select are now fixed. Opening a separate issue for the csv import shenanigans.
