### ISSUE TITLE
highlight users missing from csv in red

### ISSUE THREAD

**Issue by stevenolen** [mobilizingcs/classes#7]
to make it easier for the ~~teacher~~ coordinator to remove if they choose.

**Comment by jeroen** [comment]
This is such a strange feature. For the general case it feels really counter-intuitive to import some data and then get error colors for users that you did not import.

I implemented the same functionality in a way that is slightly less strange. When importing csv:
- newly added users are highlighted in green
- pre-existing users from csv are highlighted in light blue
- everyone else stays white.

So it is similar in functionality, but rather than red, the non-imported users just stay white. This still allows the coordinator to quickly identify which users are not in the new csv, but without making it look like something went wrong. 

This also makes much more sense from an implementation point of view, because I don't have to search the entire table for users that were not in the csv.

**Comment by hongsudt** [comment]
@jeroenooms The missing users (along with the newly added users) were highlighted green, instead of white..  

Right now you reported the number of newly added users. Can you also report # of missing users, so they can pay attention to it?

**Comment by jeroen** [comment]
OK so the issue here is what you expect to happen. I imagine that if the user imports two files with users, at the end all the users that were just added are green. I think it's strange that the users that you imported in the first file, suddenly become "missing" in the second file.

**Comment by hongsudt** [comment]
This is not strange at all... We just heard that a teacher accidentally
imported a file with 300+ users... In this case, the second one she import
will be a shorter list...

**Comment by jeroen** [comment]
How about we add a button 'delete all users' so that the teacher can easily delete all users and then import the second file? I think in the general case it is weird to remove users by importing again.

**Comment by stevenolen** [comment]
can we do checkbox batch operations? are there any others?

**Comment by hongsudt** [comment]
I like the batch deletion operation since there were at least 2 teachers
that made such mistakes (the first one imported 1000 students)..

But to me that's a different feature.. What we are discussing is that when
a user import a new file, it should be a different transaction per file
(not per session). The app adds non-existent users to the class. I am not
asking to have missing users deleted, but highlighted them so that users
can pay attention to the difference.

**Comment by jeroen** [comment]
Okay I added a feature that resets all colors when a new file is selected. So now it should work as expected.

**Comment by hongsudt** [comment]
Great! I will close this issue then..  and open another one for batch delete..
